name: Build & Deploy (Vite/Vue)

on:
  push:
    branches: [ "main" ]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      OUTPUT_DIR: dist
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Optional: sanity-check that dist isn't empty
      - name: List files
        run: |
          echo "Built files:"
          ls -la $OUTPUT_DIR

      # Upload to your server (rsync over SSH)
      - name: Deploy via SSH (rsync)
        uses: easingthemes/ssh-deploy@v5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: aira-holding.de
          REMOTE_USER: root
          TARGET: /root/aira-holding            # change to your web root
          SOURCE: ${{ env.OUTPUT_DIR }}/
          ARGS: "-rltgoDz --delete"        # atomic-ish sync
